### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
cython does not seem to pick up the CPPFLAGS, but it should: https://github.com/python/cpython/blob/33986465bde2a2188537c4ef6cdb6055e348f31f/Lib/distutils/sysconfig.py#L223

**Comment by saraedum** [comment]
(curious, that this has been reported 15 years ago upstream and is still open…)

**Comment by saraedum** [comment]
Seems I've been barking up the wrong tree here. The CXXFLAGS are picked up but just weren't set.

**Comment by saraedum** [comment]
This mostly works. Are the sage-flatsurf errors expected?

**Comment by videlec** [comment]
Nope :) Let me fix them here.

**Comment by videlec** [comment]
The issue comes from the following which seems not be supported in the CI setup (but it is with the sage-flatsurf available in conda)
```
sage: from flatsurf import ConvexPolygons                                                                                                                                                      
sage: ConvexPolygons(ZZ)                                                                                                                                                                       
ConvexPolygons(Integer Ring)
```

**Review by videlec — APPROVED** [review]

**Comment by videlec** [comment]
Many thanks for your help.

**Pull request merged**
